import { useState, useEffect, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { useProfile } from '../hooks/useProfile'
import { useTasks } from '../hooks/useTasks'
import { useWeeklyReport } from '../hooks/useWeeklyReport'
import Header from '../components/Header'
import ProgressBar from '../components/ui/ProgressBar'
import Button from '../components/ui/Button'
import { formatWeekRange, getWeekStart, toDateStr } from '../lib/dates'
import { supabase } from '../lib/supabase'

const ARENA_SLUGS = ['career', 'health', 'learning', 'misc']
const ARENA_LABELS = { career: 'Career', health: 'Health', learning: 'Learning', misc: 'Misc' }

const TREND_ICON = { up: '↑', down: '↓', flat: '→' }
const TREND_COLOR = { up: 'text-peak-success', down: 'text-[#DC2626]', flat: 'text-peak-muted' }

function parseCoach(report) {
  if (!report?.ai_summary) return null
  // Handle legacy plain-text format
  if (!report.ai_summary.trim().startsWith('{')) {
    return {
      summary: report.ai_summary,
      nextWeekCommitments: report.next_week_commitments ?? [],
    }
  }
  try {
    const parsed = JSON.parse(report.ai_summary)
    return {
      summary: parsed.summary ?? report.ai_summary,
      nextWeekCommitments: report.next_week_commitments ?? parsed.nextWeekCommitments ?? [],
    }
  } catch {
    return {
      summary: report.ai_summary,
      nextWeekCommitments: report.next_week_commitments ?? [],
    }
  }
}

export default function WeeklyReport() {
  const { weekDate } = useParams()
  const navigate = useNavigate()
  const { user } = useAuth()
  const { profile, loading: profileLoading } = useProfile(user?.id)
  const { arenas, getArenaStats, getWeekXp, loading: tasksLoading } = useTasks(user?.id)
  const { report, allReports, loading, generating, generateReport } = useWeeklyReport(user?.id, weekDate ?? null)

  const weekStartStr = weekDate ?? toDateStr(getWeekStart(new Date()))
  const weekRange = formatWeekRange(new Date(weekStartStr + 'T00:00:00Z'))
  const currentWeekStart = toDateStr(getWeekStart(new Date()))
  const isCurrentWeek = weekStartStr === currentWeekStart

  // Mathematical prev/next — never rely on allReports existing
  const prevWeekStr = toDateStr(new Date(new Date(weekStartStr + 'T00:00:00Z').getTime() - 7 * 24 * 60 * 60 * 1000))
  const nextWeekStr = toDateStr(new Date(new Date(weekStartStr + 'T00:00:00Z').getTime() + 7 * 24 * 60 * 60 * 1000))
  const twelveWeeksAgo = toDateStr(new Date(new Date(currentWeekStart + 'T00:00:00Z').getTime() - 12 * 7 * 24 * 60 * 60 * 1000))
  const canGoPrev = weekStartStr > twelveWeeksAgo
  const canGoNext = !isCurrentWeek


  const [generateError, setGenerateError] = useState(null)
  const [expandedArena, setExpandedArena] = useState(null)
  const [deepDiveData, setDeepDiveData] = useState({})
  const [deepDiving, setDeepDiving] = useState(null)

  const hasAutoGenerated = useRef(false)

  // Reset the guard each time the week changes so auto-generate fires per week
  useEffect(() => {
    hasAutoGenerated.current = false
  }, [weekStartStr])

  useEffect(() => {
    if (
      !report &&
      !loading &&
      !tasksLoading &&
      !generating &&
      !hasAutoGenerated.current &&
      !isCurrentWeek &&
      weekStartStr < currentWeekStart
    ) {
      hasAutoGenerated.current = true
      handleGenerate()
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [report, loading, tasksLoading, weekStartStr])

  async function handleGenerate() {
    setGenerateError(null)
    const breakdown = {}
    ARENA_SLUGS.forEach(slug => {
      const stats = getArenaStats(slug)
      breakdown[ARENA_LABELS[slug]] = { completed: stats.completed, total: stats.total, xp: stats.xpEarned }
    })
    try {
      await generateReport({
        tasksCompleted: Object.values(breakdown).reduce((s, a) => s + a.completed, 0),
        tasksTotal:     Object.values(breakdown).reduce((s, a) => s + a.total, 0),
        xpEarned:       getWeekXp(),
        streakHeld:     (profile?.current_streak ?? 0) > 0,
        arenaBreakdown: breakdown,
      })
    } catch (err) {
      console.error('Failed to generate report:', err)
      setGenerateError('Could not generate report. Try again.')
    }
  }

  async function handleDeepDive(arenaName, weekStats) {
    // Toggle closed if already open with data
    if (expandedArena === arenaName && deepDiveData[arenaName]) {
      setExpandedArena(null)
      return
    }
    setExpandedArena(arenaName)
    if (deepDiveData[arenaName]) return // already fetched

    setDeepDiving(arenaName)
    try {
      const { data: { session } } = await supabase.auth.getSession()
      const res = await fetch('/api/arena-deep-dive', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session?.access_token}`,
        },
        body: JSON.stringify({
          arenaName,
          weekStats,
          weekStart: weekStartStr,
          previousWeekStats: null,
        }),
      })
      if (res.ok) {
        let data = await res.json()
        // Defensive: if pattern looks like raw JSON/fenced, try to re-parse
        if (typeof data.pattern === 'string' && (data.pattern.trim().startsWith('{') || data.pattern.trim().startsWith('```'))) {
          try {
            const cleaned = data.pattern.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim()
            const inner = JSON.parse(cleaned)
            data = {
              pattern: inner.pattern ?? data.pattern,
              actionPlan: Array.isArray(inner.actionPlan) ? inner.actionPlan : data.actionPlan,
              trend: ['up', 'down', 'flat'].includes(inner.trend) ? inner.trend : data.trend,
            }
          } catch { /* use data as-is */ }
        }
        setDeepDiveData(prev => ({ ...prev, [arenaName]: data }))
      }
    } catch (err) {
      console.error('Deep dive failed:', err)
    } finally {
      setDeepDiving(null)
    }
  }

  if (loading || profileLoading || tasksLoading) {
    return (
      <div className="min-h-screen bg-peak-bg flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-peak-accent border-t-transparent rounded-full animate-spin" />
      </div>
    )
  }

  const coachData = parseCoach(report)

  return (
    <div className="min-h-screen bg-peak-bg">
      <Header profile={profile} />

      <main className="max-w-3xl mx-auto px-6 py-5 space-y-5">
        {/* Week navigation */}
        <div className="flex items-center justify-between">
          <button
            onClick={() => canGoPrev && navigate(`/report/${prevWeekStr}`)}
            disabled={!canGoPrev}
            className="text-xs text-peak-muted hover:text-peak-primary disabled:opacity-30 transition-colors"
          >
            ← Prev
          </button>
          <div className="text-center">
            <p className="text-xs font-black tracking-widest uppercase text-peak-accent">Weekly Report</p>
            <p className="text-sm font-bold text-peak-primary">{weekRange}</p>
          </div>
          <button
            onClick={() => canGoNext && navigate(nextWeekStr === currentWeekStart ? '/report' : `/report/${nextWeekStr}`)}
            disabled={!canGoNext}
            className="text-xs text-peak-muted hover:text-peak-primary disabled:opacity-30 transition-colors"
          >
            Next →
          </button>
        </div>

        {generateError && (
          <p role="alert" className="text-[#DC2626] text-xs font-medium bg-[#FEF2F2] border border-[#FCA5A5] rounded-lg px-3 py-2">
            {generateError}
          </p>
        )}

        {/* No report yet */}
        {!report && isCurrentWeek && (
          <div className="bg-peak-surface border border-peak-border rounded-xl p-6 text-center space-y-3">
            <p className="text-peak-muted text-sm">No report generated yet for this week.</p>
            <Button onClick={handleGenerate} size="lg" disabled={generating}>
              {generating ? 'Generating...' : 'Generate Report'}
            </Button>
          </div>
        )}

        {!report && !isCurrentWeek && (
          <div className="bg-peak-surface border border-peak-border rounded-xl p-6 text-center space-y-3">
            {generating ? (
              <>
                <div className="w-6 h-6 border-2 border-peak-accent border-t-transparent rounded-full animate-spin mx-auto" />
                <p className="text-peak-muted text-sm">Generating report for {weekRange}...</p>
              </>
            ) : (
              <p className="text-peak-muted text-sm">No report for this week.</p>
            )}
          </div>
        )}

        {/* Report content */}
        {report && (
          <>
            {/* Stats summary */}
            <div className="grid grid-cols-3 gap-3">
              <div className="bg-peak-surface border border-peak-border rounded-xl p-4 text-center">
                <p className="text-2xl font-black text-peak-primary">{report.tasks_completed}<span className="text-peak-muted text-base">/{report.tasks_total}</span></p>
                <p className="text-[10px] font-bold tracking-widest uppercase text-peak-muted mt-1">Tasks</p>
              </div>
              <div className="bg-peak-surface border border-peak-border rounded-xl p-4 text-center">
                <p className="text-2xl font-black text-peak-xp">{report.xp_earned}</p>
                <p className="text-[10px] font-bold tracking-widest uppercase text-peak-muted mt-1">XP</p>
              </div>
              <div className="bg-peak-surface border border-peak-border rounded-xl p-4 text-center">
                <p className="text-2xl font-black text-peak-primary">{report.streak_held ? '✓' : '✗'}</p>
                <p className="text-[10px] font-bold tracking-widest uppercase text-peak-muted mt-1">Streak</p>
              </div>
            </div>

            {/* Arena breakdown with Dig Deeper */}
            <div className="bg-peak-surface border border-peak-border rounded-xl p-4">
              <p className="text-[10px] font-black tracking-widest uppercase text-peak-muted mb-3">Arena Breakdown</p>
              <div className="space-y-1">
                {Object.entries(report.arena_breakdown || {}).map(([name, stats]) => {
                  const isExpanded = expandedArena === name
                  const dive = deepDiveData[name]
                  const isDiving = deepDiving === name
                  return (
                    <div key={name}>
                      <div className="py-2">
                        <div className="flex items-center justify-between mb-1.5">
                          <div className="flex items-center gap-2">
                            <span className="text-sm font-medium text-peak-primary">{name}</span>
                            {dive && (
                              <span className={`text-xs font-bold px-1.5 py-0.5 rounded-full ${
                                dive.trend === 'up'   ? 'bg-[#D1FAE5] text-[#059669]' :
                                dive.trend === 'down' ? 'bg-[#FEE2E2] text-[#DC2626]' :
                                                        'bg-peak-elevated text-[#D97706]'
                              }`}>
                                {dive.trend === 'up' ? '↑' : dive.trend === 'down' ? '↓' : '→'}
                              </span>
                            )}
                          </div>
                          <div className="flex items-center gap-3">
                            <span className="text-xs text-peak-accent font-bold">{stats.xp} XP · {stats.completed}/{stats.total}</span>
                            <button
                              onClick={() => handleDeepDive(name, { completed: stats.completed, total: stats.total, xpEarned: stats.xp })}
                              className="text-xs text-peak-accent hover:text-peak-primary transition-colors font-medium"
                            >
                              {isDiving ? 'Loading...' : isExpanded && dive ? 'Close ↑' : 'Dig deeper →'}
                            </button>
                          </div>
                        </div>
                        <ProgressBar value={stats.completed} max={Math.max(stats.total, 1)} />
                      </div>

                      {/* Deep dive panel */}
                      {isExpanded && dive && (
                        <div className="mb-2 bg-peak-elevated border border-peak-border rounded-lg p-4 space-y-3">
                          <p className="text-sm text-peak-text leading-relaxed">{dive.pattern}</p>
                          {dive.actionPlan?.length > 0 && (
                            <div>
                              <p className="text-[9px] font-bold tracking-widest uppercase text-peak-muted mb-2">Action Plan</p>
                              <ol className="space-y-2">
                                {dive.actionPlan.map((step, i) => (
                                  <li key={i} className="flex gap-2.5">
                                    <span className="shrink-0 text-sm font-bold text-peak-accent">{i + 1}.</span>
                                    <span className="text-sm text-peak-primary leading-snug">{step.replace(/^\d+\.\s*/, '')}</span>
                                  </li>
                                ))}
                              </ol>
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  )
                })}
              </div>
            </div>

            {/* AI Coach */}
            {coachData && (
              <div className="bg-peak-accent-light border border-peak-accent/30 rounded-xl p-5 space-y-4">
                <div>
                  <p className="text-[10px] font-black tracking-widest uppercase text-peak-accent mb-2">AI Coach</p>
                  <p className="text-sm text-peak-primary leading-relaxed">{coachData.summary}</p>
                </div>

                {coachData.nextWeekCommitments?.length > 0 && (
                  <div>
                    <p className="text-[10px] font-black tracking-widest uppercase text-peak-accent mb-2">Next Week's Focus</p>
                    <ol className="space-y-2">
                      {coachData.nextWeekCommitments.map((c, i) => (
                        <li key={i} className="flex items-start gap-3">
                          <span className="shrink-0 w-5 h-5 rounded border-2 border-peak-accent/50 mt-0.5" />
                          <span className="text-sm text-peak-primary leading-snug">{c.replace(/^\d+\.\s*/, '')}</span>
                        </li>
                      ))}
                    </ol>
                  </div>
                )}
              </div>
            )}

            {/* Regenerate */}
            {isCurrentWeek && (
              <div className="text-center">
                <Button variant="ghost" size="sm" onClick={handleGenerate} disabled={generating}>
                  {generating ? 'Regenerating...' : 'Regenerate'}
                </Button>
              </div>
            )}
          </>
        )}
      </main>
    </div>
  )
}
