import { useState, useEffect, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { useProfile } from '../hooks/useProfile'
import { useTasks } from '../hooks/useTasks'
import { useWeeklyReport } from '../hooks/useWeeklyReport'
import { useBig3, BIG3_START_DATE } from '../hooks/useBig3'
import TopBar from '../components/TopBar'
import ProgressBar from '../components/ui/ProgressBar'
import Button from '../components/ui/Button'
import { formatWeekRange, getWeekStart, toDateStr } from '../lib/dates'
import { supabase } from '../lib/supabase'

const ARENA_SLUGS = ['career', 'health', 'learning', 'misc']
const ARENA_LABELS = { career: 'Career', health: 'Health', learning: 'Learning', misc: 'Misc' }

const TREND_ICON = { up: '↑', down: '↓', flat: '→' }
const TREND_COLOR = { up: 'text-peak-success', down: 'text-[#DC2626]', flat: 'text-peak-muted' }

function parseCoach(report) {
  if (!report?.ai_summary) return null
  const stripped = report.ai_summary.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim()
  if (!stripped.startsWith('{')) {
    return {
      summary: stripped,
      nextWeekCommitments: report.next_week_commitments ?? [],
    }
  }
  try {
    const parsed = JSON.parse(stripped)
    return {
      summary: parsed.summary ?? stripped,
      nextWeekCommitments: report.next_week_commitments ?? parsed.nextWeekCommitments ?? [],
    }
  } catch {
    return {
      summary: stripped,
      nextWeekCommitments: report.next_week_commitments ?? [],
    }
  }
}

export default function WeeklyReport() {
  const { weekDate } = useParams()
  const navigate = useNavigate()
  const { user } = useAuth()
  const { profile, loading: profileLoading } = useProfile(user?.id)
  const { arenas, getArenaStats, getWeekXp, loading: tasksLoading } = useTasks(user?.id)
  const { report, allReports, loading, generating, generateReport } = useWeeklyReport(user?.id, weekDate ?? null)
  const { big3ByDate } = useBig3(user?.id, weekStartStr)

  const weekStartStr = weekDate ?? toDateStr(getWeekStart(new Date()))
  const weekRange = formatWeekRange(new Date(weekStartStr + 'T00:00:00Z'))
  const currentWeekStart = toDateStr(getWeekStart(new Date()))
  const isCurrentWeek = weekStartStr === currentWeekStart

  // Mathematical prev/next — never rely on allReports existing
  const prevWeekStr = toDateStr(new Date(new Date(weekStartStr + 'T00:00:00Z').getTime() - 7 * 24 * 60 * 60 * 1000))
  const nextWeekStr = toDateStr(new Date(new Date(weekStartStr + 'T00:00:00Z').getTime() + 7 * 24 * 60 * 60 * 1000))
  const twelveWeeksAgo = toDateStr(new Date(new Date(currentWeekStart + 'T00:00:00Z').getTime() - 12 * 7 * 24 * 60 * 60 * 1000))
  const canGoPrev = weekStartStr > twelveWeeksAgo
  const canGoNext = !isCurrentWeek


  const [generateError, setGenerateError] = useState(null)
  const [expandedArena, setExpandedArena] = useState(null)
  const [deepDiveData, setDeepDiveData] = useState({})
  const [deepDiving, setDeepDiving] = useState(null)

  const hasAutoGenerated = useRef(false)

  // Reset the guard each time the week changes so auto-generate fires per week
  useEffect(() => {
    hasAutoGenerated.current = false
  }, [weekStartStr])

  useEffect(() => {
    if (
      !report &&
      !loading &&
      !tasksLoading &&
      !generating &&
      !hasAutoGenerated.current &&
      !isCurrentWeek &&
      weekStartStr < currentWeekStart
    ) {
      hasAutoGenerated.current = true
      handleGenerate()
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [report, loading, tasksLoading, weekStartStr])

  async function handleGenerate() {
    setGenerateError(null)
    const breakdown = {}
    ARENA_SLUGS.forEach(slug => {
      const stats = getArenaStats(slug)
      breakdown[ARENA_LABELS[slug]] = { completed: stats.completed, total: stats.total, xp: stats.xpEarned }
    })
    try {
      await generateReport({
        tasksCompleted: Object.values(breakdown).reduce((s, a) => s + a.completed, 0),
        tasksTotal:     Object.values(breakdown).reduce((s, a) => s + a.total, 0),
        xpEarned:       getWeekXp(),
        streakHeld:     (profile?.current_streak ?? 0) > 0,
        arenaBreakdown: breakdown,
      })
    } catch (err) {
      console.error('Failed to generate report:', err)
      setGenerateError('Could not generate report. Try again.')
    }
  }

  async function handleDeepDive(arenaName, weekStats) {
    // Toggle closed if already open with data
    if (expandedArena === arenaName && deepDiveData[arenaName]) {
      setExpandedArena(null)
      return
    }
    setExpandedArena(arenaName)
    if (deepDiveData[arenaName]) return // already fetched

    setDeepDiving(arenaName)
    try {
      const { data: { session } } = await supabase.auth.getSession()
      const res = await fetch('/api/arena-deep-dive', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session?.access_token}`,
        },
        body: JSON.stringify({
          arenaName,
          weekStats,
          weekStart: weekStartStr,
          previousWeekStats: null,
        }),
      })
      if (res.ok) {
        let data = await res.json()
        // Defensive: if pattern looks like raw JSON/fenced, try to re-parse
        if (typeof data.pattern === 'string' && (data.pattern.trim().startsWith('{') || data.pattern.trim().startsWith('```'))) {
          try {
            const cleaned = data.pattern.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim()
            const inner = JSON.parse(cleaned)
            data = {
              pattern: inner.pattern ?? data.pattern,
              actionPlan: Array.isArray(inner.actionPlan) ? inner.actionPlan : data.actionPlan,
              trend: ['up', 'down', 'flat'].includes(inner.trend) ? inner.trend : data.trend,
            }
          } catch { /* use data as-is */ }
        }
        setDeepDiveData(prev => ({ ...prev, [arenaName]: data }))
      }
    } catch (err) {
      console.error('Deep dive failed:', err)
    } finally {
      setDeepDiving(null)
    }
  }

  if (loading || profileLoading || tasksLoading) {
    return (
      <div className="min-h-screen bg-peak-bg flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-peak-accent border-t-transparent rounded-full animate-spin" />
      </div>
    )
  }

  const coachData = parseCoach(report)

  return (
    <div className="flex flex-col h-full overflow-hidden">
      <TopBar
        title="Weekly Report"
        subtitle={weekRange}
        action={
          <div className="flex items-center gap-2">
            <button
              onClick={() => canGoPrev && navigate(`/report/${prevWeekStr}`)}
              disabled={!canGoPrev}
              className="text-xs text-peak-muted hover:text-peak-text px-2 py-1 rounded-lg hover:bg-peak-bg transition-colors disabled:opacity-30"
            >
              ← Prev
            </button>
            <button
              onClick={() => canGoNext && navigate(nextWeekStr === currentWeekStart ? '/report' : `/report/${nextWeekStr}`)}
              disabled={!canGoNext}
              className="text-xs text-peak-muted hover:text-peak-text px-2 py-1 rounded-lg hover:bg-peak-bg transition-colors disabled:opacity-30"
            >
              Next →
            </button>
          </div>
        }
      />
      <main className="flex-1 overflow-y-auto bg-peak-bg p-6">
        <div className="max-w-3xl mx-auto space-y-5">
          {generateError && (
            <p role="alert" className="text-[#DC2626] text-xs font-medium bg-[#FEF2F2] border border-[#FCA5A5] rounded-lg px-3 py-2">
              {generateError}
            </p>
          )}

          {/* No report yet */}
          {!report && isCurrentWeek && (
            <div className="bg-peak-surface border border-peak-border rounded-xl p-6 text-center space-y-3">
              <p className="text-peak-muted text-sm">No report generated yet for this week.</p>
              <Button onClick={handleGenerate} size="lg" disabled={generating}>
                {generating ? 'Generating...' : 'Generate Report'}
              </Button>
            </div>
          )}

          {!report && !isCurrentWeek && (
            <div className="bg-peak-surface border border-peak-border rounded-xl p-6 text-center space-y-3">
              {generating ? (
                <>
                  <div className="w-6 h-6 border-2 border-peak-accent border-t-transparent rounded-full animate-spin mx-auto" />
                  <p className="text-peak-muted text-sm">Generating report for {weekRange}...</p>
                </>
              ) : (
                <p className="text-peak-muted text-sm">No report for this week.</p>
              )}
            </div>
          )}

          {/* Big 3 Consistency — shown whenever week has days >= BIG3_START_DATE */}
          {(() => {
            const now = new Date()
            const todayLocal = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`
            // Mon–Fri for this week
            const weekdays = Array.from({ length: 5 }, (_, i) => {
              const d = new Date(weekStartStr + 'T00:00:00Z')
              d.setUTCDate(d.getUTCDate() + i)
              return d.toISOString().slice(0, 10)
            }).filter(d => d >= BIG3_START_DATE)
            if (weekdays.length === 0) return null
            const DAY_LABELS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
            const validDays = weekdays.filter(d => d <= todayLocal)
            const setCount = validDays.filter(d => big3ByDate[d]).length
            return (
              <div className="bg-peak-surface border border-peak-border rounded-xl p-4">
                <div className="flex items-center justify-between mb-3">
                  <p className="text-[10px] font-semibold tracking-widest uppercase text-peak-muted">Big 3 Consistency</p>
                  <span className="text-xs font-semibold text-peak-accent">{setCount} of {validDays.length} days</span>
                </div>
                <div className="flex gap-2">
                  {weekdays.map((dateStr, i) => {
                    const isSet = !!big3ByDate[dateStr]
                    const isPast = dateStr <= todayLocal
                    const big3 = big3ByDate[dateStr]
                    return (
                      <div key={dateStr} className="flex-1 flex flex-col items-center gap-1">
                        <span className="text-[10px] font-semibold text-peak-muted">{DAY_LABELS[i]}</span>
                        <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm border-2 transition-colors ${
                          isSet
                            ? 'bg-peak-accent border-peak-accent text-white'
                            : isPast
                            ? 'border-[#DC2626] text-[#DC2626]'
                            : 'border-peak-border text-peak-muted'
                        }`}>
                          {isSet ? '✓' : isPast ? '✗' : '·'}
                        </div>
                        {big3 && (
                          <div className="w-full space-y-0.5">
                            {[big3.item_1, big3.item_2, big3.item_3].filter(Boolean).map((item, j) => (
                              <p key={j} className="text-[9px] text-peak-muted leading-tight truncate text-center">{item}</p>
                            ))}
                          </div>
                        )}
                      </div>
                    )
                  })}
                </div>
              </div>
            )
          })()}

          {/* Report content */}
          {report && (
            <>
              {/* Stats summary */}
              <div className="grid grid-cols-3 gap-3">
                <div className="bg-peak-surface border border-peak-border rounded-xl p-4 text-center">
                  <p className="text-2xl font-black text-peak-text">{report.tasks_completed}<span className="text-peak-muted text-base">/{report.tasks_total}</span></p>
                  <p className="text-[10px] font-semibold tracking-widest uppercase text-peak-muted mt-1">Tasks</p>
                </div>
                <div className="bg-peak-surface border border-peak-border rounded-xl p-4 text-center">
                  <p className="text-2xl font-black text-peak-accent">{report.xp_earned}</p>
                  <p className="text-[10px] font-semibold tracking-widest uppercase text-peak-muted mt-1">XP</p>
                </div>
                <div className="bg-peak-surface border border-peak-border rounded-xl p-4 text-center">
                  <p className="text-2xl font-black text-peak-text">{report.streak_held ? '✓' : '✗'}</p>
                  <p className="text-[10px] font-semibold tracking-widest uppercase text-peak-muted mt-1">Streak</p>
                </div>
              </div>

              {/* Arena breakdown with Dig Deeper */}
              <div className="bg-peak-surface border border-peak-border rounded-xl p-4">
                <p className="text-[10px] font-semibold tracking-widest uppercase text-peak-muted mb-3">Arena Breakdown</p>
                <div className="space-y-1">
                  {Object.entries(report.arena_breakdown || {}).map(([name, stats]) => {
                    const isExpanded = expandedArena === name
                    const dive = deepDiveData[name]
                    const isDiving = deepDiving === name
                    return (
                      <div key={name}>
                        <div className="py-2">
                          <div className="flex items-center justify-between mb-1.5">
                            <div className="flex items-center gap-2">
                              <span className="text-sm font-medium text-peak-text">{name}</span>
                              {dive && (
                                <span className={`text-xs font-bold px-1.5 py-0.5 rounded-full ${
                                  dive.trend === 'up'   ? 'bg-[#D1FAE5] text-[#059669]' :
                                  dive.trend === 'down' ? 'bg-[#FEE2E2] text-[#DC2626]' :
                                                          'bg-peak-bg text-[#D97706]'
                                }`}>
                                  {dive.trend === 'up' ? '↑' : dive.trend === 'down' ? '↓' : '→'}
                                </span>
                              )}
                            </div>
                            <div className="flex items-center gap-3">
                              <span className="text-xs text-peak-accent font-bold">{stats.xp} XP · {stats.completed}/{stats.total}</span>
                              <button
                                onClick={() => handleDeepDive(name, { completed: stats.completed, total: stats.total, xpEarned: stats.xp })}
                                className="text-xs text-peak-accent hover:text-peak-text transition-colors font-medium"
                              >
                                {isDiving ? 'Loading...' : isExpanded && dive ? 'Close ↑' : 'Dig deeper →'}
                              </button>
                            </div>
                          </div>
                          <ProgressBar value={stats.completed} max={Math.max(stats.total, 1)} />
                        </div>

                        {/* Deep dive panel */}
                        {isExpanded && dive && (
                          <div className="mb-2 bg-peak-bg border border-peak-border rounded-lg p-4 space-y-3">
                            <p className="text-[15px] text-peak-text leading-[1.7]">{dive.pattern}</p>
                            {dive.actionPlan?.length > 0 && (
                              <div>
                                <p className="text-[9px] font-semibold tracking-widest uppercase text-peak-muted mb-2">Action Plan</p>
                                <ol className="space-y-2">
                                  {dive.actionPlan.map((step, i) => (
                                    <li key={i} className="flex gap-2.5">
                                      <span className="shrink-0 text-sm font-bold text-peak-accent">{i + 1}.</span>
                                      <span className="text-sm text-peak-text leading-snug">{step.replace(/^\d+\.\s*/, '')}</span>
                                    </li>
                                  ))}
                                </ol>
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    )
                  })}
                </div>
              </div>

              {/* AI Coach */}
              {coachData && (
                <div className="bg-peak-accent-light border border-peak-accent/30 rounded-xl p-5 space-y-4">
                  <div>
                    <p className="text-[10px] font-semibold tracking-widest uppercase text-peak-accent mb-2">AI Coach</p>
                    <p className="text-[15px] text-peak-text leading-[1.7]">{coachData.summary}</p>
                  </div>

                  {coachData.nextWeekCommitments?.length > 0 && (
                    <div>
                      <p className="text-[10px] font-semibold tracking-widest uppercase text-peak-accent mb-2">Next Week's Focus</p>
                      <ol className="space-y-2">
                        {coachData.nextWeekCommitments.map((c, i) => (
                          <li key={i} className="flex items-start gap-3">
                            <span className="shrink-0 w-5 h-5 rounded border-2 border-peak-accent/50 mt-0.5" />
                            <span className="text-sm text-peak-text leading-snug">{c.replace(/^\d+\.\s*/, '')}</span>
                          </li>
                        ))}
                      </ol>
                    </div>
                  )}
                </div>
              )}

              {/* Regenerate */}
              {isCurrentWeek && (
                <div className="text-center">
                  <Button variant="ghost" size="sm" onClick={handleGenerate} disabled={generating}>
                    {generating ? 'Regenerating...' : 'Regenerate'}
                  </Button>
                </div>
              )}
            </>
          )}
        </div>
      </main>
    </div>
  )
}
